import {
  aongaHighStreetPrintRetroImg,
  appleCollectionImg,
  armorCardSlotIphoneCaseImg,
  beanBagsBigWImg,
  betterHomesGardensBazaarImg,
  caseCompatibleSamsungGalaxyImg,
  cottonHeadNeckArabScarfImg,
  cottonKeffiyehTacticalDesertImg,
  cupsImg,
  dinningSetImg,
  dopeShirtHoodieImg,
  earringsImg,
  faithOverFearHoodieImg,
  fashionHoodedJacketMenImg, 
  gadgetSetWithStandImg,
  homeBarImg,
  img1Img,
  inkachWomenFashionCasualSkirtImg,
  iphone16ProAltImg,
  iphone16ProImg,
  iphoneCaseImg,
  klassischesHerbstImg,
  knifeImg
} from "../constants";

export const products = [
  {
    id: "1ty-kjk-3rt-51",
    image: gadgetSetWithStandImg,
    name: "Premium Gadget Set with Stand",
    price: { currentPrice: "#24,999", oldPrice: "#34,999" },
    ratings: 4.6,
  },
  {
    id: "1ty-kjk-3rt-52",
    image: homeBarImg,
    name: "Modern Home Bar Set",
    price: { currentPrice: "#75,000", oldPrice: "#95,000" },
    ratings: 4.7,
  },
  {
    id: "1ty-kjk-3rt-53",
    image: img1Img,
    name: "Lifestyle Collection Set",
    price: { currentPrice: "#29,999", oldPrice: "#39,999" },
    ratings: 4.3,
  },
  {
    id: "1ty-kjk-3rt-54",
    image: inkachWomenFashionCasualSkirtImg,
    name: "Inkach Women's Casual Skirt",
    price: { currentPrice: "#12,500", oldPrice: "#18,999" },
    ratings: 4.4,
  },
  {
    id: "1ty-kjk-3rt-55",
    image: iphone16ProImg,
    name: "iPhone 16 Pro Case",
    price: { currentPrice: "#15,999", oldPrice: "#22,999" },
    ratings: 4.8,
  },
  {
    id: "1ty-kjk-3rt-56",
    image: iphone16ProAltImg,
    name: "iPhone 16 Pro Alt Case",
    price: { currentPrice: "#14,999", oldPrice: "#21,999" },
    ratings: 4.5,
  },
  {
    id: "1ty-kjk-3rt-57",
    image: iphoneCaseImg,
    name: "Classic iPhone Protection Case",
    price: { currentPrice: "#9,999", oldPrice: "#15,999" },
    ratings: 4.2,
  },
  {
    id: "1ty-kjk-3rt-58",
    image: klassischesHerbstImg,
    name: "Klassisches Herbst Collection",
    price: { currentPrice: "#35,999", oldPrice: "#45,999" },
    ratings: 4.6,
  },
  {
    id: "1ty-kjk-3rt-59",
    image: knifeImg,
    name: "Professional Kitchen Knife Set",
    price: { currentPrice: "#28,999", oldPrice: "#38,999" },
    ratings: 4.7,
  },
  {
    id: "1ty-kjk-3rt-37",
    image: aongaHighStreetPrintRetroImg,
    name: "Aonga High-StreetPrint Retro",
    price: { currentPrice: "#13,004", oldPrice: "#21,548" },
    ratings: 4.5,
  },
  {
    id: "1ty-kjk-3rt-38",
    image: fashionHoodedJacketMenImg,
    name: "Men's Lightweight Breathable Sneakers",
    price: { currentPrice: "#14,250", oldPrice: "#22,990" },
    ratings: 4.0,
  },
  {
    id: "1ty-kjk-3rt-39",
    image: appleCollectionImg,
    name: "Apple Collection Sports Edition",
    price: { currentPrice: "#18,600", oldPrice: "#25,300" },
    ratings: 4.2,
  },
  {
    id: "1ty-kjk-3rt-40",
    image: armorCardSlotIphoneCaseImg,
    name: "Armor Card Slot iPhone Case",
    price: { currentPrice: "#19,990", oldPrice: "#28,400" },
    ratings: 4.7,
  },
  {
    id: "1ty-kjk-3rt-41",
    image: beanBagsBigWImg,
    name: "Bean Bags Big W Collection",
    price: { currentPrice: "#15,500", oldPrice: "#23,900" },
    ratings: 4.3,
  },
  {
    id: "1ty-kjk-3rt-42",
    image: betterHomesGardensBazaarImg,
    name: "Better Homes Gardens Bazaar Set",
    price: { currentPrice: "#45,000", oldPrice: "#65,000" },
    ratings: 4.8,
  },
  {
    id: "1ty-kjk-3rt-43",
    image: caseCompatibleSamsungGalaxyImg,
    name: "Samsung Galaxy Compatible Case",
    price: { currentPrice: "#8,999", oldPrice: "#12,999" },
    ratings: 4.4,
  },
  {
    id: "1ty-kjk-3rt-44",
    image: cottonHeadNeckArabScarfImg,
    name: "Cotton Head Neck Arab Scarf",
    price: { currentPrice: "#5,999", oldPrice: "#9,999" },
    ratings: 4.1,
  },
  {
    id: "1ty-kjk-3rt-45",
    image: cottonKeffiyehTacticalDesertImg,
    name: "Cotton Keffiyeh Tactical Desert Scarf",
    price: { currentPrice: "#6,500", oldPrice: "#10,900" },
    ratings: 4.3,
  },
  {
    id: "1ty-kjk-3rt-46",
    image: cupsImg,
    name: "Premium Coffee Cups Set",
    price: { currentPrice: "#12,500", oldPrice: "#18,900" },
    ratings: 4.6,
  },
  {
    id: "1ty-kjk-3rt-47",
    image: dinningSetImg,
    name: "Luxury Dining Set Collection",
    price: { currentPrice: "#89,999", oldPrice: "#120,000" },
    ratings: 4.9,
  },
  {
    id: "1ty-kjk-3rt-48",
    image: dopeShirtHoodieImg,
    name: "Dope Shirt Hoodie Premium",
    price: { currentPrice: "#11,999", oldPrice: "#17,999" },
    ratings: 4.2,
  },
  {
    id: "1ty-kjk-3rt-49",
    image: earringsImg,
    name: "Fashion Statement Earrings",
    price: { currentPrice: "#4,999", oldPrice: "#7,999" },
    ratings: 4.4,
  },
  {
    id: "1ty-kjk-3rt-50",
    image: faithOverFearHoodieImg,
    name: "Faith Over Fear Hoodie",
    price: { currentPrice: "#13,500", oldPrice: "#19,999" },
    ratings: 4.5,
  }
];
